spring.application.name=user-service

# Default profile
spring.profiles.active=dev

# Profile groups for common + environment-specific configs
spring.profiles.group.dev=dev,common
spring.profiles.group.test=test,common
spring.profiles.group.prod=prod,common
